<p>This error is quite self-descriptive:</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
</pre></td><td class="rouge-code"><pre><span class="n">Traceback</span> <span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="n">File</span> <span class="s">"users.py"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">25</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
    <span class="n">user</span> <span class="o">=</span> <span class="n">users</span><span class="p">[</span><span class="mi">0</span><span class="p">]</span>
<span class="nb">TypeError</span><span class="p">:</span> <span class="s">'NoneType'</span> <span class="nb">object</span> <span class="ow">is</span> <span class="ow">not</span> <span class="n">subscriptable</span>
</pre></td></tr></tbody></table></code></pre></div></div>

<p>It means that you are trying to subscript (index) the object that actually is None. In the above example, the <code class="highlighter-rouge">users</code> list is empty so you can’t get the first user from it since None object doesn’t define the <a href="https://docs.python.org/3/reference/datamodel.html#object.__getitem__"><code class="highlighter-rouge">__getitem__</code></a> method. This simply can be fixed by finding out <code class="highlighter-rouge">Why the list is None</code>.</p>
